export default {
    editor: {
        label: {
            en: "Streak Tracking Calendar",
        },
        icon: "calendar",
        bubble: {
            icon: "calendar",
        },
    },
    triggerEvents: [
        { name: 'onDateClick', label: { en: 'On Date Click' }, event: { date: '' } },
        { name: 'onPrevMonth', label: { en: 'On Previous Month' }, event: { newDate: '' } },
        { name: 'onNextMonth', label: { en: 'On Next Month' }, event: { newDate: '' } },
    ],
    properties: {
        sectionData: {
            type: 'SectionHeader',
            label: { en: 'Data' },
            section: 'settings',
        },
        currentDate: {
            label: { en: "Reference Date" },
            type: "Date",
            defaultValue: new Date().toISOString(),
            bindable: true,
            section: "settings",
            /* The calendar will show the month of this date */
        },
        user_id: {
            label: { en: "User ID" },
            type: "Number",
            defaultValue: 10,
            bindable: true,
            section: "settings",
        },
        dates: {
            label: { en: "Completed Dates" },
            type: "Array",
            bindable: true,
            defaultValue: [],
            section: "settings",
            /* Expects array of ISO Date Strings e.g. ["2023-10-01"] */
        },

        sectionColors: {
            type: 'SectionHeader',
            label: { en: 'Colors & Shape' },
            section: 'settings',
        },
        emptyColor: {
            label: { en: "None Date Color" },
            type: "Color",
            defaultValue: "#F3F4F6",
            bindable: true,
            section: 'settings',
        },
        dateBoxColor1: {
            label: { en: "Some Date Colour" },
            type: "Color",
            bindable: true,
            defaultValue: "#4F46E5",
            section: 'settings',
        },
        dateBoxColor2: {
            label: { en: "Lots Date Colour" },
            type: "Color",
            bindable: true,
            defaultValue: "#10B981",
            section: 'settings',
        },
        textColor: {
            label: { en: "Text Color" },
            type: "Color",
            defaultValue: "#111827",
            bindable: true,
            section: 'settings',
        },
        borderRadius: {
            label: { en: "Border Radius" },
            type: "Length",
            defaultValue: "8px",
            section: 'settings',
        },
        dayCellGap: {
            label: { en: "Day Cell Gap" },
            type: "Length",
            bindable: true,
            defaultValue: "8px",
            section: 'settings',
        },
        calendarPadding: {
            label: { en: "Calendar Padding" },
            type: "Length",
            bindable: true,
            defaultValue: "16px",
            section: 'settings',
            desc: { en: "Internal padding to prevent the Today circle from being cut off" }
        },

        sectionToday: {
            type: 'SectionHeader',
            label: { en: 'Today Indicator' },
            section: 'settings',
        },
        todayCircleColor: {
            label: { en: "Today Circle Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#2563EB",
            section: 'settings',
        },
        todayTextColor: {
            label: { en: "Today Text Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#FFFFFF",
            section: 'settings',
        },
        todayCircleSize: {
            label: { en: "Circle Size" },
            type: "Length",
            bindable: true,
            defaultValue: "32px",
            section: 'settings',
        },
        todayFontSize: {
            label: { en: "Number Font Size" },
            type: "Length",
            bindable: true,
            defaultValue: "14px",
            section: 'settings',
        },
        todayCircleBorderColor: {
            label: { en: "Border Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#FFFFFF",
            section: 'settings',
        },
        todayCircleBorderWidth: {
            label: { en: "Border Width" },
            type: "Length",
            bindable: true,
            defaultValue: "0px",
            section: 'settings',
        },

        sectionTarget: {
            type: 'SectionHeader',
            label: { en: 'Target Date (Cross)' },
            section: 'settings',
        },
        targetDate: {
            label: { en: "Target Date" },
            type: "Date",
            defaultValue: 1765065600000,
            bindable: true,
            section: 'settings',
            desc: { en: "Date or Timestamp number" }
        },
        targetCrossColor: {
            label: { en: "Cross Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#EF4444",
            section: 'settings',
        },
        targetCrossSize: {
            label: { en: "Cross Size" },
            type: "Length",
            bindable: true,
            defaultValue: "24px",
            section: 'settings',
        },
        targetCrossWidth: {
            label: { en: "Cross Thickness" },
            type: "Length",
            bindable: true,
            defaultValue: "3px",
            section: 'settings',
        },

        sectionTypography: {
            type: 'SectionHeader',
            label: { en: 'Typography' },
            section: 'settings',
        },
        globalFontFamily: {
            label: { en: "Font Family" },
            type: "FontFamily",
            defaultValue: "",
            section: 'settings',
        },
        headerFontSize: {
            label: { en: "Month Title Size" },
            type: "Length",
            defaultValue: "20px",
            section: 'settings',
        },
        titleVerticalOffset: {
            label: { en: "Title Vertical Offset" },
            type: "Length",
            defaultValue: "-7px",
            bindable: true,
            defaultValue: "0px",
            section: 'settings',
        },
        monthYearBottomMargin: {
            label: { en: "Month/Year Bottom Margin" },
            type: "Length",
            defaultValue: "6px",
            bindable: true,
            section: 'settings',
        },
        monthTitleColor: {
            label: { en: "Month Title Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#222",
            section: 'settings',
        },
        monthYearGap: {
            label: { en: "Month-Year Gap" },
            type: "Length",
            defaultValue: "12px",
            bindable: true,
            section: 'settings',
        },
        yearFontSize: {
            label: { en: "Year Size" },
            type: "Length",
            defaultValue: "19px",
            section: 'settings',
        },
        yearTextColor: {
            label: { en: "Year Text Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#888",
            section: 'settings',
        },
        daysFontSize: {
            label: { en: "Weekday Labels Size" },
            type: "Length",
            defaultValue: "12px",
            section: 'settings',
        },
        weekdayCalendarGap: {
            label: { en: "Weekday to Calendar Gap" },
            type: "Length",
            bindable: true,
            defaultValue: "8px",
            section: 'settings',
        },
        weekdayTextColor: {
            label: { en: "Weekday Text Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#7c7c7c",
            section: 'settings',
        },
        arrowIconColor: {
            label: { en: "Arrow Icon Color" },
            type: "Color",
            bindable: true,
            defaultValue: "#111827",
            section: 'settings',
        },
        dayCellHoverScale: {
            label: { en: "Day Cell Hover Scale" },
            type: "Number",
            bindable: true,
            defaultValue: 0.9,
            section: 'settings',
        },
        arrowIconRadius: {
            label: { en: "Arrow Icon Border Radius" },
            type: "Length",
            bindable: true,
            defaultValue: "50%",
            section: 'settings',
        },
    },
};